Update build script

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-set -e
+# exit on error, unset vars
+set -eu
+# exit early for errors in pipelines
+set -o pipefail
+# debugging
+# set -x
 
 usage() {
     echo "Usage: $0 [-n] [-d diff] major_version minor_version patch_version" 1>&2
@@ -9,6 +14,7 @@ usage() {
 
 # Options
 cache=""
+diff=""
 while getopts ":d:n" opt; do
   case $opt in
     n)
@@ -34,7 +40,7 @@ fi
 v_minor=$version_major.$version_minor
 v_full=$version_major.$version_minor.$version_patch
 echo
-echo Building $v_full
+echo Building "$v_full"
 echo
 
 set -o xtrace
@@ -42,17 +48,17 @@ set -o xtrace
 ## Dockerfile
 
 write_version () {
-    sed -i '' -E "s/^FROM httpd:([0-9\.]+)$/FROM httpd:${v_full}/" $1
+    sed -i '' -E "s/^FROM httpd:([0-9\.]+)$/FROM httpd:${v_full}/" "$1"
 }
 write_version Dockerfile
 
 ## Build
 
 # build image
-docker build $cache -f Dockerfile -t drupal-web:httpd-${v_full} .
+docker build $cache -f Dockerfile -t "drupal-web:httpd-${v_full}" .
 
 # post-build config
-docker run --rm drupal-web:httpd-${v_full} /bin/cat /usr/local/apache2/conf/httpd.conf-default > \
+docker run --rm "drupal-web:httpd-${v_full}" /bin/cat /usr/local/apache2/conf/httpd.conf-default > \
     conf/httpd.conf-default
 
 set +e
