add tests

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -14,13 +14,17 @@ EOF
 # Options
 cache=
 diff=
-while getopts ":nd:vh" opt; do
+run_tests=
+while getopts ":nd:tvh" opt; do
     case $opt in
         n)
             cache=--no-cache
             ;;
         d)
             diff=$OPTARG
+            ;;
+        t)
+            run_tests=yes
             ;;
         v)
             set -x
@@ -79,6 +83,39 @@ curl https://raw.githubusercontent.com/nginxinc/nginx-wiki/master/source/start/t
 
 # build image
 docker build $cache -f Dockerfile -t "drupal-web:nginx-${v_full}" .
+
+# tests
+if [[ ! -z "$run_tests" ]]; then
+
+    network=docker-drupal-web
+    docker network create -d bridge "$network" > /dev/null
+    php=$(docker run --rm -d --network "$network" --name php -v /var/www/html tbfisher/drupal-php:7.1-dev)
+    nginx=$(docker run --rm -d -P --expose 80 --network "$network" --volumes-from "$php" -v /var/www/html -v /etc/nginx "drupal-web:nginx-${v_full}")
+
+    # https://github.com/yandex/gixy
+    test_gixy=$(docker run --rm --volumes-from "$nginx" yandex/gixy -f json /etc/nginx/nginx.conf)
+
+    # curl phpinfo
+    docker exec "$nginx" /bin/sh -c 'apt-get -qq update; apt-get -yqq install curl; echo "<?php phpinfo();" > /var/www/html/index.php' > /dev/null
+    test_phpinfo=$(docker exec "$nginx" /bin/sh -c 'curl -sSIL http://localhost | grep "HTTP/1.1 200 OK"' | sed -e 's/[[:space:]]*$//')
+
+    # clean up
+    docker rm -f "$nginx" "$php" > /dev/null
+    docker network rm "$network" > /dev/null
+
+    # test output
+    if [ "$(echo "$test_gixy" | jq 'length')" != 0 ]; then
+        echo gixy test failed.
+        echo "$test_gixy" | jq
+        exit 1
+    fi
+    if [ "$test_phpinfo" != 'HTTP/1.1 200 OK' ]; then
+        echo curl phpinfo failed.
+        exit 1
+    fi
+
+    echo tests pass.
+fi
 
 set +e
 
