Update build script
# Conflicts:
#	bin/build

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -1,6 +1,11 @@
 #!/bin/bash
 
-set -e
+# exit on error, unset vars
+set -eu
+# exit early for errors in pipelines
+set -o pipefail
+# debugging
+# set -x
 
 usage() {
     echo "Usage: $0 [-n] [-d diff] major_version minor_version patch_version" 1>&2
@@ -9,6 +14,7 @@ usage() {
 
 # Options
 cache=""
+diff=""
 while getopts ":d:n" opt; do
   case $opt in
     n)
@@ -34,7 +40,7 @@ fi
 v_minor=$version_major.$version_minor
 v_full=$version_major.$version_minor.$version_patch
 echo
-echo Building $v_full
+echo Building "$v_full"
 echo
 
 set -o xtrace
@@ -42,14 +48,14 @@ set -o xtrace
 ## Dockerfile
 
 write_version () {
-    sed -i '' -E "s/^FROM nginx:([0-9\.]+)$/FROM nginx:${v_full}/" $1
+    sed -i '' -E "s/^FROM nginx:([0-9\.]+)$/FROM nginx:${v_full}/" "$1"
 }
 write_version Dockerfile
 
 ## Build
 
 # pre-build config
-curl -L https://raw.githubusercontent.com/nginx/nginx/branches/stable-${v_minor}/conf/nginx.conf > \
+curl -L "https://raw.githubusercontent.com/nginx/nginx/branches/stable-${v_minor}/conf/nginx.conf" > \
     conf/nginx.conf-default
 curl https://raw.githubusercontent.com/nginxinc/nginx-wiki/master/source/start/topics/recipes/drupal.rst | \
     pandoc -f rst -t json | \
@@ -57,7 +63,7 @@ curl https://raw.githubusercontent.com/nginxinc/nginx-wiki/master/source/start/t
     conf/drupal.conf-default
 
 # build image
-docker build $cache -f Dockerfile -t drupal-web:nginx-${v_full} .
+docker build $cache -f Dockerfile -t "drupal-web:nginx-${v_full}" .
 
 set +e
 
